Add types
ThaUnknown/simple-peer pull request #49
Opened 2024-12-21 06:33 UTC by nichoth

[ ] Documentation update
[ ] Bug fix
[x] New feature
[x] Other, please explain:

Add typescript for better DX.

I'm not sure if anyone is interested in adding types, but they exist, and here they are. The tests all pass for me.

2024-12-25 00:34 UTC, KW-M requested changes
Thanks @nichoth! I think having typing in SimplePeer is a great addition! @ThaUnknown is full typing something you would consider merging? - I've been editing the "ice restart" PR I submitted based on feedback and I'll rebase those changes on the final version of this PR if both are likely to get merged. 

### A couple easy issues to fix before merging
1. Esbuild currently [doesn't output .d.ts files](https://github.com/evanw/esbuild/issues/95) so users of the published package won't actually get type checking.
2. Using package.json "exports" will [break SimplePeer imports for some users of the NPM package](https://stackoverflow.com/a/72275458/28594063). Sadly, popular build tools & IDEs (notably VSCode and the default Typescript compiler) still [default to NOT following the package.json "exports" field](https://www.typescriptlang.org/tsconfig/#moduleResolution) unless moduleResolution is set to "node16" or later in the end user's project. 

### Proposed fixes (tested)
 
tsconfig.json:
```js
{
  compilerOptions: {
    // built js (and d.ts) files go in the root of the repo, just like before this PR:
    "outDir: ".",
    "declarationDir": ".",
    ...
  },
 ...
}
```

package.json
 ```js
{
  "files": [
    "./*.js",
    "./*.js.map",
    "./*.d.ts",
    "./*.d.ts.map"
  ],
  // - "exports": not needed anymore
  "devDependencies": {
    "typescript": "^5.7.2",
    // - "esbuild" - not using because it unfortunately can't generate .d.ts files.
    ...
  },
  "scripts": {
    "clean": "rm -rf ./*.js && rm -rf ./*.js.map && rm -rf ./*.d.ts && rm -rf ./*.d.ts.map",
    "build": "npm run clean && tsc --project tsconfig.build.json",
    ...
  }
  ...
}
```

These changes make the built repo look a lot like the repo did before this PR and ends up publishing a flat hierarchy with the .js (and .d.ts) files at the top level of the repo/package alongside package.json, and so imports remain the same. Also I switched from EsBuild to the regular TSC compiler to get type definitions (.d.ts) 

Have a good holiday season!

2024-12-25 02:43 UTC, nichoth commented
> Esbuild currently https://github.com/evanw/esbuild/issues/95 so users of the published package won't actually get type checking.

woops I totally missed that; [my template](https://github.com/nichoth/template-ts-browser) is configured to build types as a separate command. I just pushed an update for that.

-------

> Using package.json "exports" will [break SimplePeer imports for some users of the NPM package](https://stackoverflow.com/a/72275458/28594063).

That's interesting; I didn't know about that.

2024-12-25 03:06 UTC, KW-M commented
Thanks!! Looks good.
One Tiny typo: Build tsc command still ends with /dist

2024-12-25 18:45 UTC, ThaUnknown commented
I'll have to review this later as I'm currently busy, but this defo needs eslint

2025-01-05 16:51 UTC, ThaUnknown commented
hey @nichoth thanks for the PR, as mentioned previously, this needs to be linted, for which I made https://github.com/thaunknown/eslint-config-standard-universal, if you're not interesting in fixing all the errors this will cause tell me and I'll have to fix it myself, most of which relates to the use of any, which is disallowed

I also noticed you re-declare a lot of W3C types for webrtc, there's no need to do that, simply use @types/webrtc

2025-01-05 18:22 UTC, nichoth commented
Thanks @ThaUnknown . It might be a while before I get back to this, as work is moving in a different direction. I will close this since I don't have bandwidth right now.

2025-01-05 18:22 UTC, closed without merging